//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public long purchaseId { get; set; }
        public long productId { get; set; }
        public long card_number { get; set; }
        public int targetPostalCode { get; set; }
        public double prize { get; set; }
        public int quantity { get; set; }
        public System.DateTime date { get; set; }
        public string descriptiveName { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_Purchase_Card
        /// </summary>
        public virtual Card Card { get; set; }
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_Purchase_Product
        /// </summary>
        public virtual Product Product { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + card_number.GetHashCode();
    			hash = hash * multiplier + targetPostalCode.GetHashCode();
    			hash = hash * multiplier + prize.GetHashCode();
    			hash = hash * multiplier + quantity.GetHashCode();
    			hash = hash * multiplier + date.GetHashCode();
    			hash = hash * multiplier + (descriptiveName == null ? 0 : descriptiveName.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type? 
    
            Purchase target = obj as Purchase;
    
    		return true
               &&  (this.purchaseId == target.purchaseId )       
               &&  (this.productId == target.productId )       
               &&  (this.card_number == target.card_number )       
               &&  (this.targetPostalCode == target.targetPostalCode )       
               &&  (this.prize == target.prize )       
               &&  (this.quantity == target.quantity )       
               &&  (this.date == target.date )       
               &&  (this.descriptiveName == target.descriptiveName )       
               ;
    
        }
    
    
    	public static bool operator ==(Purchase  objA, Purchase  objB)
        {
            // Check if the objets are the same Purchase entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Purchase  objA, Purchase  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strPurchase = new StringBuilder();
    
    		strPurchase.Append("[ ");
           strPurchase.Append(" purchaseId = " + purchaseId + " | " );       
           strPurchase.Append(" productId = " + productId + " | " );       
           strPurchase.Append(" card_number = " + card_number + " | " );       
           strPurchase.Append(" targetPostalCode = " + targetPostalCode + " | " );       
           strPurchase.Append(" prize = " + prize + " | " );       
           strPurchase.Append(" quantity = " + quantity + " | " );       
           strPurchase.Append(" date = " + date + " | " );       
           strPurchase.Append(" descriptiveName = " + descriptiveName + " | " );       
            strPurchase.Append("] ");    
    
    		return strPurchase.ToString();
        }
    
    
    }
}
