//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Es.Udc.DotNet.PracticaMaD.Model
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public Workshop()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public long workshopId { get; set; }
        public string workshop_name { get; set; }
        public int postal_code { get; set; }
        public string Country { get; set; }
    
        
        /// <summary>
        /// Relationship Name (Foreign Key in ER-Model): FK_Usuario_Workshop
        /// </summary>
        public virtual ICollection<Usuario> Usuario { get; set; }
    
    	/// <summary>
    	/// A hash code for this instance, suitable for use in hashing algorithms and data structures 
    	/// like a hash table. It uses the Josh Bloch implementation from "Effective Java"
        /// Primary key of entity is not included in the hash calculation to avoid errors
    	/// with Entity Framework creation of key values.
    	/// </summary>
    	/// <returns>
    	/// Returns a hash code for this instance.
    	/// </returns>
    	public override int GetHashCode()
    	{
    	    unchecked
    	    {
    			int multiplier = 31;
    			int hash = GetType().GetHashCode();
    
    			hash = hash * multiplier + (workshop_name == null ? 0 : workshop_name.GetHashCode());
    			hash = hash * multiplier + postal_code.GetHashCode();
    			hash = hash * multiplier + (Country == null ? 0 : Country.GetHashCode());
    
    			return hash;
    	    }
    
    	}
        
        /// <summary>
        /// Compare this object against another instance using a value approach (field-by-field) 
        /// </summary>
        /// <remarks>See http://www.loganfranken.com/blog/687/overriding-equals-in-c-part-1/ for detailed info </remarks>
    	public override bool Equals(object obj)
    	{
    
            if (ReferenceEquals(null, obj)) return false;        // Is Null?
            if (ReferenceEquals(this, obj)) return true;         // Is same object?
            if (obj.GetType() != this.GetType()) return false;   // Is same type? 
    
            Workshop target = obj as Workshop;
    
    		return true
               &&  (this.workshopId == target.workshopId )       
               &&  (this.workshop_name == target.workshop_name )       
               &&  (this.postal_code == target.postal_code )       
               &&  (this.Country == target.Country )       
               ;
    
        }
    
    
    	public static bool operator ==(Workshop  objA, Workshop  objB)
        {
            // Check if the objets are the same Workshop entity
            if(Object.ReferenceEquals(objA, objB))
                return true;
      
            return objA.Equals(objB);
    }
    
    
    	public static bool operator !=(Workshop  objA, Workshop  objB)
        {
            return !(objA == objB);
        }
    
    
        /// <summary>
        /// Returns a <see cref="T:System.String"></see> that represents the 
        /// current <see cref="T:System.Object"></see>.
        /// </summary>
        /// <returns>
        /// A <see cref="T:System.String"></see> that represents the current 
        /// <see cref="T:System.Object"></see>.
        /// </returns>
    	public override String ToString()
    	{
    	    StringBuilder strWorkshop = new StringBuilder();
    
    		strWorkshop.Append("[ ");
           strWorkshop.Append(" workshopId = " + workshopId + " | " );       
           strWorkshop.Append(" workshop_name = " + workshop_name + " | " );       
           strWorkshop.Append(" postal_code = " + postal_code + " | " );       
           strWorkshop.Append(" Country = " + Country + " | " );       
            strWorkshop.Append("] ");    
    
    		return strWorkshop.ToString();
        }
    
    
    }
}
